// This file is auto-generated by @hey-api/openapi-ts

export type AccountPublic = {
  current_balance?: string;
  income?: string;
  expenses?: string;
  id: string;
  owner_id: string;
  created_at?: string | null;
};

export type Body_login_login_access_token = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

export type BudgetCreate = {
  maximum: number | string;
  theme: string;
  category_id: string;
};

export type BudgetPublic = {
  maximum: string;
  theme: string;
  id: string;
  account_id: string;
  category_id: string;
  created_at?: string | null;
};

export type BudgetUpdate = {
  maximum?: number | string | null;
  theme?: string | null;
  category_id?: string | null;
};

export type CategoryPublic = {
  name: string;
  id: string;
  account_id: string;
  created_at?: string | null;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type Message = {
  message: string;
};

export type PotCreate = {
  name: string;
  target: number | string;
  total?: number | string;
  theme: string;
};

export type PotPublic = {
  name: string;
  target: string;
  total?: string;
  theme: string;
  id: string;
  account_id: string;
  created_at?: string | null;
};

export type PotTransfer = {
  amount: number | string;
};

export type PotUpdate = {
  name?: string | null;
  target?: number | string | null;
  total?: number | string | null;
  theme?: string | null;
};

export type RecurringBillsSummary = {
  total_bills: string;
  paid_count: number;
  paid_total: string;
  upcoming_count: number;
  upcoming_total: string;
  due_soon_count: number;
  due_soon_total: string;
};

export type Token = {
  access_token: string;
  token_type?: string;
};

export type TransactionPublic = {
  counterparty_name: string;
  avatar_url?: string | null;
  posted_at: string;
  amount: string;
  is_recurring?: boolean;
  id: string;
  account_id: string;
  category_id: string;
  created_at?: string | null;
};

export type UserCreate = {
  email: string;
  password: string;
};

export type UserPublic = {
  email: string;
  id: string;
  created_at?: string | null;
};

export type UserRegister = {
  email: string;
  password: string;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input?: unknown;
  ctx?: {
    [key: string]: unknown;
  };
};

export type AccountReadAccountMeResponse = AccountPublic;

export type BudgetsReadBudgetsResponse = Array<BudgetPublic>;

export type BudgetsCreateBudgetData = {
  requestBody: BudgetCreate;
};

export type BudgetsCreateBudgetResponse = BudgetPublic;

export type BudgetsUpdateBudgetData = {
  budgetId: string;
  requestBody: BudgetUpdate;
};

export type BudgetsUpdateBudgetResponse = BudgetPublic;

export type BudgetsDeleteBudgetData = {
  budgetId: string;
};

export type BudgetsDeleteBudgetResponse = Message;

export type CategoriesReadCategoriesResponse = Array<CategoryPublic>;

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = Token;

export type LoginTestTokenResponse = UserPublic;

export type PotsReadPotsResponse = Array<PotPublic>;

export type PotsCreatePotData = {
  requestBody: PotCreate;
};

export type PotsCreatePotResponse = PotPublic;

export type PotsUpdatePotData = {
  potId: string;
  requestBody: PotUpdate;
};

export type PotsUpdatePotResponse = PotPublic;

export type PotsDeletePotData = {
  potId: string;
};

export type PotsDeletePotResponse = Message;

export type PotsAddToPotData = {
  potId: string;
  requestBody: PotTransfer;
};

export type PotsAddToPotResponse = PotPublic;

export type PotsWithdrawFromPotData = {
  potId: string;
  requestBody: PotTransfer;
};

export type PotsWithdrawFromPotResponse = PotPublic;

export type TransactionsReadTransactionsData = {
  categoryId?: string | null;
  isRecurring?: boolean | null;
  limit?: number;
  search?: string | null;
  skip?: number;
  sortBy?: string;
};

export type TransactionsReadTransactionsResponse = Array<TransactionPublic>;

export type TransactionsCountTransactionsData = {
  categoryId?: string | null;
  isRecurring?: boolean | null;
  search?: string | null;
};

export type TransactionsCountTransactionsResponse = number;

export type TransactionsSpendingByCategoryResponse = {
  [key: string]: string;
};

export type TransactionsRecurringBillsSummaryResponse = RecurringBillsSummary;

export type UsersCreateUserData = {
  requestBody: UserCreate;
};

export type UsersCreateUserResponse = UserPublic;

export type UsersReadUserMeResponse = UserPublic;

export type UsersDeleteUserMeResponse = Message;

export type UsersRegisterUserData = {
  requestBody: UserRegister;
};

export type UsersRegisterUserResponse = UserPublic;

export type UsersReadUserByIdData = {
  userId: string;
};

export type UsersReadUserByIdResponse = UserPublic;

export type UsersDeleteUserData = {
  userId: string;
};

export type UsersDeleteUserResponse = Message;

export type UtilsTestEmailData = {
  emailTo: string;
};

export type UtilsTestEmailResponse = Message;

export type UtilsHealthCheckResponse = boolean;
